// THIS FILE IS AUTOGENERATED BY `src/parser/analysis_table_generator.rs`
// DO NOT MODIFY THIS FILE DIRECTLY
// INSTEAD MODIFY THE SOURCE FILES AND RE-RUN THE GENERATOR SCRIPT
use crate::common::types::token::Token;
use crate::parser::lexem::Lexem;
use std::collections::HashMap;
use std::mem::{discriminant, Discriminant};
pub struct AnalysisTable {
    table: [HashMap<Discriminant<Token>, Vec<Lexem>>; 5],
}

impl AnalysisTable {
    pub fn get(&self, id: &usize, token: &Token) -> Option<&Vec<Lexem>> {
        self.table[*id].get(&discriminant(token))
    }
}

pub fn get_analysis_table() -> AnalysisTable {
    let analysis_table = AnalysisTable {
        table: [
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)],
                ),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::Add),
                    vec![
                        Lexem::Terminal(Token::Add),
                        Lexem::NonTerminal(2),
                        Lexem::NonTerminal(1),
                    ],
                ),
                (discriminant(&Token::CloseParenthesis), Vec::new()),
                (discriminant(&Token::EOF), Vec::new()),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::NonTerminal(4), Lexem::NonTerminal(3)],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![Lexem::NonTerminal(4), Lexem::NonTerminal(3)],
                ),
            ]),
            HashMap::from([
                (discriminant(&Token::Add), Vec::new()),
                (
                    discriminant(&Token::Mult),
                    vec![
                        Lexem::Terminal(Token::Mult),
                        Lexem::NonTerminal(4),
                        Lexem::NonTerminal(3),
                    ],
                ),
                (discriminant(&Token::CloseParenthesis), Vec::new()),
                (discriminant(&Token::EOF), Vec::new()),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::Terminal(Token::integer(0))],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![
                        Lexem::Terminal(Token::OpenParenthesis),
                        Lexem::NonTerminal(0),
                        Lexem::Terminal(Token::CloseParenthesis),
                    ],
                ),
            ]),
        ],
    };
    return analysis_table;
}
