// THIS FILE IS AUTOGENERATED BY `src/parser/analysis_table_generator.rs`
// DO NOT MODIFY THIS FILE DIRECTLY
// INSTEAD MODIFY THE SOURCE FILES AND RE-RUN THE GENERATOR SCRIPT
use std::collections::HashMap;
use crate::parser::lexem::Lexem;
use crate::common::types::token::Token;
pub struct AnalysisTable {
    table: [HashMap<Token, Vec<Lexem>>; 5],
}

impl AnalysisTable {
    pub fn get(&self, id: &usize, token: &Token) -> Option<&Vec<Lexem>> {
        self.table[*id].get(token)
    }
}

pub fn get_analysis_table() -> AnalysisTable {
    let analysis_table = AnalysisTable {
        table: [
            HashMap::from([(Token::integer(0), vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)]), (Token::OpenBracket, vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)])]),
            HashMap::from([(Token::Add, vec![Lexem::Terminal(Token::Add), Lexem::NonTerminal(2), Lexem::NonTerminal(1)]), (Token::CloseBracket, Vec::new()), (Token::EOF, Vec::new())]),
            HashMap::from([(Token::integer(0), vec![Lexem::NonTerminal(4),Lexem::NonTerminal(3)]), (Token::OpenBracket, vec![Lexem::NonTerminal(4),Lexem::NonTerminal(3)])]),
            HashMap::from([(Token::Add, Vec::new()), (Token::Mult, vec![Lexem::Terminal(Token::Mult), Lexem::NonTerminal(4), Lexem::NonTerminal(3)]), (Token::CloseBracket, Vec::new()), (Token::EOF, Vec::new())]), 
            HashMap::from([(Token::integer(0), vec![Lexem::Terminal(Token::integer(0))]), (Token::OpenBracket, vec![Lexem::Terminal(Token::OpenBracket), Lexem::NonTerminal(0), Lexem::Terminal(Token::CloseBracket)])]),
            ]
    };
    return analysis_table;
}