// use crate::parser::lexem::Lexem;
// use std::string::String;
// use std::fs::File;
// struct AnalysisTable {
//     table: Vec<Vec<Option<Vec<Lexem>>>>,
// }

// pub fn generate_analysis_table() {
//     // ...
// }

// pub fn analyse_grammar() {
//     // ...
// }

// pub fn generate_source_file(filename: &str) {
//     let _file = File::open(filename).unwrap();
    
//     let mut generated_file = String::from("// THIS FILE IS AUTOGENERATED BY `src/parser/analysis_table_generator.rs`\n");
//     generated_file.push_str("// DO NOT MODIFY THIS FILE DIRECTLY\n");
//     generated_file.push_str("// INSTEAD MODIFY THE SOURCE FILES AND RE-RUN THE GENERATOR SCRIPT\n");
//     generated_file.push_str("use crate::parser::lexem::Lexem;\n");
//     generated_file.push_str("pub struct AnalysisTable {\n");
//     generated_file.push_str("    table: [HashMap<Token, Vec<Lexem>>; 3],\n");
//     generated_file.push_str("}\n");
// }