// THIS FILE IS AUTOGENERATED BY `src/parser/analysis_table_generator.rs`
// DO NOT MODIFY THIS FILE DIRECTLY
// INSTEAD MODIFY THE SOURCE FILES AND RE-RUN THE GENERATOR SCRIPT
use std::collections::HashMap;
use crate::parser::lexem::Lexem;
use crate::common::types::token::Token;
pub struct AnalysisTable {
    table: [HashMap<Token, Vec<Lexem>>; 3],
}

pub fn get_analysis_table() -> AnalysisTable {
    let analysis_table = AnalysisTable {
        table: [
            HashMap::from([(Token::Add, vec![Lexem::Terminal(Token::Add)])]),
            HashMap::from([(Token::Sub, vec![Lexem::Terminal(Token::Sub)])]),
            HashMap::from([(Token::Mult, vec![Lexem::Terminal(Token::Mult)])]),
            ]
    };
    return analysis_table;
}