/***************************************************/
/* THIS FILE IS AUTOMATICALLY GENERATED            */
/* BY `src/generator/analysis_table_generator.rs`. */
/* DO NOT EDIT THIS FILE MANUALLY                  */
/***************************************************/

use super::analysis_table::AnalysisTable;
use super::analysis_table_generator::generate_analysis_table;
use crate::common::types::token::Token;
use crate::parser::lexem::Lexem;
use std::collections::HashMap;
use std::mem::discriminant;

pub fn get_analysis_table() -> AnalysisTable {

    return generate_analysis_table("grammaire.txt")

    /*
    let analysis_table = AnalysisTable {
        non_terminal_names: Vec::new(),
        table: vec![
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![Lexem::NonTerminal(2), Lexem::NonTerminal(1)],
                ),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::Add),
                    vec![
                        Lexem::Terminal(Token::Add),
                        Lexem::NonTerminal(2),
                        Lexem::NonTerminal(1),
                    ],
                ),
                (discriminant(&Token::CloseParenthesis), Vec::new()),
                (discriminant(&Token::EOF), Vec::new()),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::NonTerminal(4), Lexem::NonTerminal(3)],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![Lexem::NonTerminal(4), Lexem::NonTerminal(3)],
                ),
            ]),
            HashMap::from([
                (discriminant(&Token::Add), Vec::new()),
                (
                    discriminant(&Token::Mult),
                    vec![
                        Lexem::Terminal(Token::Mult),
                        Lexem::NonTerminal(4),
                        Lexem::NonTerminal(3),
                    ],
                ),
                (discriminant(&Token::CloseParenthesis), Vec::new()),
                (discriminant(&Token::EOF), Vec::new()),
            ]),
            HashMap::from([
                (
                    discriminant(&Token::integer(0)),
                    vec![Lexem::Terminal(Token::integer(0))],
                ),
                (
                    discriminant(&Token::OpenParenthesis),
                    vec![
                        Lexem::Terminal(Token::OpenParenthesis),
                        Lexem::NonTerminal(0),
                        Lexem::Terminal(Token::CloseParenthesis),
                    ],
                ),
            ]),
        ],
    };
    return analysis_table;
    */
}