use indoc::writedoc;
use std::collections::HashSet;
use std::fmt;

use super::super::analysis_table::AnalysisTable;
use super::generic_token_repr;
use crate::analysis_table::formatters::construct_string_table;
use crate::analysis_table::NonTerminal;
use crate::common::types::Token;
use crate::parser::Lexem;

//TODO: Add enum Display + From<String> (see generated_table.rs)

/// Get the string of the rust code that constructs the given token
macro_rules! token_constructor {
    ($token: expr) => {
        match &$token {
            Token::Integer(n) => format!("Token::Integer(NumToken {{value: {}}})", n.value),
            Token::String(s) => format!("Token::String(String::from(\"{}\"))", s.escape_debug()),
            Token::Identifier(idt) => format!(
                "Token::Identifier(IdToken {{id: {}, name: String::new()}})",
                idt.id
            ),
            _ => format!("Token::{:?}", $token),
        }
    };
}

/// Convertit un nom de non terminal en identifiant d'enum
fn non_terminal_to_enum_name(name: &String) -> String {
    let mut enum_name = String::new();
    let mut capitalize = true;

    for c in name.chars() {
        if c.is_alphanumeric() {
            if capitalize {
                enum_name += &c.to_uppercase().to_string();
                capitalize = false;
            } else {
                enum_name.push(c);
            }
        } else {
            capitalize = true;
        }
    }

    return enum_name;
}

impl AnalysisTable {
    /// Formate la table d'analyse dans un format markdown
    pub fn display_rust<'a>(&'a self, with_comments: bool) -> impl fmt::Display + 'a {
        struct RustAnalysisTable<'a> {
            table: &'a AnalysisTable,
            with_comments: bool,
        }

        impl<'a> fmt::Display for RustAnalysisTable<'a> {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                let (_, _, nonterm_list) = construct_string_table(&self.table);

                let non_terminal_names: Vec<String> =
                    nonterm_list.iter().map(NonTerminal::to_string).collect();

                let non_terminal_enum_names: Vec<String> = non_terminal_names
                    .iter()
                    .map(non_terminal_to_enum_name)
                    .collect();

                // File header
                writedoc!(
                    f,
                    r#"
                    /***************************************************/
                    /* THIS FILE IS AUTOMATICALLY GENERATED            */
                    /* BY `src/generator/analysis_table_generator.rs`. */
                    /* DO NOT EDIT THIS FILE MANUALLY                  */
                    /***************************************************/

                    use crate::common::types::{{IdToken, NumToken, FloatToken, Token}};
                    use crate::parser::Lexem;
                    use super::analysis_table::AnalysisTable;
                    use std::collections::{{HashMap, HashSet}};
                    use std::mem::{{discriminant, Discriminant}};
                    use std::fmt::Display;

                    #[derive(Clone, PartialEq, Eq, Debug, Hash)]
                    pub enum NonTerminal {{
                "#
                )?;

                // Non terminal enum
                for name in &non_terminal_enum_names {
                    writeln!(f, "   {},", name.escape_debug())?;
                }

                writedoc!(
                    f,
                    r#"
                    }}

                    impl Display for NonTerminal {{
                        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
                            match self {{
                "#
                )?;

                for i in 0..non_terminal_enum_names.len() {
                    let name = &non_terminal_names[i];
                    let enum_name = &non_terminal_enum_names[i];
                    writeln!(
                        f,
                        "           NonTerminal::{} => write!(f, \"{}\"),",
                        enum_name,
                        name.escape_debug()
                    )?;
                }

                writeln!(f, "        }}")?;
                writeln!(f, "    }}")?;
                writeln!(f, "}}\n")?;

                writedoc!(
                    f,
                    r#"
                    impl From<String> for NonTerminal {{
                        fn from(value: String) -> Self {{
                            match value.as_str() {{
                "#
                )?;

                for i in 0..non_terminal_enum_names.len() {
                    let name = &non_terminal_names[i];
                    let enum_name = &non_terminal_enum_names[i];
                    writeln!(
                        f,
                        "           \"{}\" => NonTerminal::{},",
                        name.escape_debug(),
                        enum_name
                    )?;
                }
                writeln!(
                    f,
                    "           name => panic!(\"Invalid non terminal {{}}\", name),"
                )?;

                writeln!(f, "        }}")?;
                writeln!(f, "    }}")?;
                writeln!(f, "}}\n")?;

                writedoc!(
                    f,
                    r#"

                    pub fn get_analysis_table() -> AnalysisTable {{

                "#
                )?;

                // Used non terminals
                writeln!(
                    f,
                    "    let used_non_terminals: HashSet<NonTerminal> = HashSet::from(["
                )?;

                for name in &non_terminal_enum_names {
                    writeln!(f, "        NonTerminal::{},", name)?;
                }

                writeln!(f, "    ]);\n")?;

                // discriminant tokens
                writeln!(f, "    let tokens_discriminants: HashMap<Discriminant<Token>, Token> = HashMap::from([")?;

                let used_tokens: HashSet<Token> =
                    HashSet::from_iter(self.table.tokens_discriminants.values().cloned());

                for token in used_tokens {
                    write!(f, "        ")?;
                    writeln!(
                        f,
                        "(discriminant(&{}), {}),",
                        token_constructor!(token),
                        token_constructor!(token)
                    )?;
                }
                writeln!(f, "    ]);\n")?;

                // table
                writeln!(f, "    let table: HashMap<NonTerminal, HashMap<Discriminant<Token>, Vec<Lexem>>> = HashMap::from([")?;

                for (nonterm, row) in &self.table.table {
                    // Add comment with the name of the current non terminal
                    if self.with_comments {
                        writeln!(f, "\n        // {}", nonterm.to_string())?;
                    }

                    writeln!(
                        f,
                        "        (NonTerminal::{}, HashMap::from([",
                        non_terminal_to_enum_name(&nonterm.to_string())
                    )?;

                    for (discr, word) in row {
                        if self.with_comments {
                            let word_str: String = word
                                .iter()
                                .map(|lexem| match lexem {
                                    Lexem::NonTerminal(nt) => nt.to_string(),
                                    Lexem::Terminal(token) => generic_token_repr!(token),
                                })
                                .collect();

                            // Ex :
                            // // <E> -> <E>*<F>
                            writeln!(
                                f,
                                "\n            // {} : {} -> {}",
                                self.table.tokens_discriminants[&discr],
                                nonterm.to_string(),
                                word_str
                            )?;
                        }

                        writeln!(f, "            (")?;
                        writeln!(
                            f,
                            "                discriminant(&{}),",
                            token_constructor!(self.table.tokens_discriminants[&discr])
                        )?;

                        writeln!(f, "                vec![")?;

                        for lexem in word {
                            write!(f, "                    ")?;
                            match lexem {
                                Lexem::NonTerminal(nt) => writeln!(
                                    f,
                                    "Lexem::NonTerminal(NonTerminal::{}),",
                                    non_terminal_to_enum_name(&nt.to_string())
                                ),
                                Lexem::Terminal(token) => {
                                    writeln!(f, "Lexem::Terminal({}),", token_constructor!(token))
                                }
                            }?;
                        }

                        writeln!(f, "                ]")?;
                        writeln!(f, "            ),")?;
                    }

                    writeln!(f, "        ])),")?;
                }

                writeln!(f, "    ]);\n")?;

                // Return generated table
                writedoc!(
                    f,
                    r#"
                        return AnalysisTable {{
                            table,
                            tokens_discriminants,
                            used_non_terminals,
                        }};
                    }}
                "#
                )?;
                Ok(())
            }
        }
        RustAnalysisTable {
            table: self,
            with_comments,
        }
    }
}

#[cfg(test)]
#[macro_use]
mod tests {

    use super::*;
    use crate::common::types::{IdToken, NumToken};

    #[test]
    fn test_token_constructor_macro() {
        assert_eq!("Token::Add", token_constructor!(Token::Add));
        assert_eq!("Token::EOF", token_constructor!(Token::EOF));
        assert_eq!(
            "Token::Integer(NumToken {value: 42})",
            token_constructor!(Token::Integer(NumToken { value: 42 }))
        );
        assert_eq!(
            "Token::Identifier(IdToken {id: 12, name: String::new()})",
            token_constructor!(Token::Identifier(IdToken {
                id: 12,
                name: String::new()
            }))
        );
        assert_eq!(
            "Token::String(String::from(\"Hello, World !\"))",
            token_constructor!(Token::String(String::from("Hello, World !")))
        );
        assert_eq!(
            "Token::String(String::from(\"Escape \\\" \\n \\\\ chars\"))",
            token_constructor!(Token::String(String::from("Escape \" \n \\ chars")))
        );
    }

    #[test]
    fn test_non_terminal_to_enum() {
        assert_eq!("File", non_terminal_to_enum_name(&String::from("<file>")));
        assert_eq!(
            "Capitalizefirst",
            non_terminal_to_enum_name(&String::from("capitalizefirst"))
        );
        assert_eq!(
            "MultipleWords",
            non_terminal_to_enum_name(&String::from("multiple_words"))
        );
        assert_eq!(
            "WordsWithSmthg",
            non_terminal_to_enum_name(&String::from("<words_with_smthg>"))
        );
    }
}
