use std::collections::HashSet;
use std::fmt;
use indoc::writedoc;

use crate::common::types::token::Token;
use crate::parser::lexem::Lexem;
use super::generic_token_repr;
use super::super::analysis_table::AnalysisTable;

/// Get the string of the rust code that constructs the given token
macro_rules! token_constructor {
    ($token: expr) => {
        match &$token {
            Token::Integer(n) => format!("Token::Integer(NumToken {{value: {}}})", n.value),
            Token::String(s) => format!("Token::String(String::from(\"{}\"))", s.escape_debug()),
            Token::Identifier(idt) => format!("Token::Identifier(IdToken {{id: {}}})", idt.id),
            _ => format!("Token::{:?}", $token),
        }
    };
}

impl AnalysisTable {
    
    /// Formate la table d'analyse dans un format markdown
    pub fn display_rust<'a>(&'a self, with_comments: bool) -> impl fmt::Display + 'a {

        struct RustAnalysisTable<'a> {
            table: &'a AnalysisTable,
            with_comments: bool,
        }

        impl<'a> fmt::Display for RustAnalysisTable<'a> {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {

                // File header
                writedoc!(f, r#"
                    /***************************************************/
                    /* THIS FILE IS AUTOMATICALLY GENERATED            */
                    /* BY `src/generator/analysis_table_generator.rs`. */
                    /* DO NOT EDIT THIS FILE MANUALLY                  */
                    /***************************************************/

                    use crate::common::types::token::{{IdToken, NumToken, Token}};
                    use crate::parser::lexem::Lexem;
                    use super::analysis_table::AnalysisTable;
                    use std::collections::HashMap;
                    use std::mem::{{discriminant, Discriminant}};

                    pub fn get_analysis_table() -> AnalysisTable {{

                        let non_terminal_names: Vec<String> = vec![
                "#)?;


                // Non terminal names
                for name in &self.table.non_terminal_names {
                    writeln!(f, "        String::from(\"{}\"),", name.escape_debug())?;
                }

                writeln!(f, "    ];\n")?;


                // discriminant tokens
                writeln!(f, "    let discriminant_tokens: HashMap<Discriminant<Token>, Token> = HashMap::from([")?;
                
                let used_tokens: HashSet<Token> = HashSet::from_iter(self.table.discriminant_tokens.values().cloned());

                for token in used_tokens {
                    write!(f, "        ")?;
                    writeln!(f, "(discriminant(&{}), {}),", token_constructor!(token), token_constructor!(token))?;
                }
                writeln!(f, "    ]);\n")?;

                
                // table
                writeln!(f, "    let table: Vec<HashMap<Discriminant<Token>, Vec<Lexem>>> = vec![")?;

                for (id, row) in self.table.table.iter().enumerate() {

                    // Add comment with the name of the current non terminal
                    if self.with_comments {
                        writeln!(f, "\n        // {}", self.table.non_terminal_names[id])?;
                    }

                    writeln!(f, "        HashMap::from([")?;


                    for (discr, word) in row {

                        if self.with_comments {

                            let word_str: String = word.iter()
                                .map(|lexem| {
                                    match lexem {
                                        Lexem::NonTerminal(id) => self.table.non_terminal_names[*id].clone(),
                                        Lexem::Terminal(token) => generic_token_repr!(token),
                                    }
                                })
                                .collect();

                            // Ex :
                            // // <E> -> <E>*<F>
                            writeln!(f, "\n            // {} : {} -> {}", self.table.discriminant_tokens[discr], self.table.non_terminal_names[id], word_str)?;
                        }

                        writeln!(f, "            (")?;
                        writeln!(f, "                discriminant(&{}),", token_constructor!(self.table.discriminant_tokens[discr]))?;

                        writeln!(f, "                vec![")?;

                        for lexem in word {
                            write!(f, "                    ")?;
                            match lexem {
                                Lexem::NonTerminal(id) => writeln!(f, "Lexem::NonTerminal({id}),"),
                                Lexem::Terminal(token) => writeln!(f, "Lexem::Terminal({}),", token_constructor!(token)),
                            }?;
                        }

                        writeln!(f, "                ]")?;
                        writeln!(f, "            ),")?;
                    }

                    writeln!(f, "        ]),")?;
                }

                writeln!(f, "    ];\n")?;


                // Return generated table
                writedoc!(f, r#"
                        return AnalysisTable {{
                            table,
                            non_terminal_names,
                            discriminant_tokens,
                        }};
                    }}
                "#)?;
                Ok(())
            }
        }
        RustAnalysisTable {
            table: self,
            with_comments,
        }
    }
}


#[cfg(test)]
#[macro_use]
mod tests {

    use crate::common::types::token::{IdToken, NumToken};
    use super::*;

    #[test]
    fn test_token_constructor_macro() {
        assert_eq!("Token::Add", token_constructor!(Token::Add));
        assert_eq!("Token::EOF", token_constructor!(Token::EOF));
        assert_eq!("Token::Integer(NumToken {value: 42})", token_constructor!(Token::Integer(NumToken {value: 42})));
        assert_eq!("Token::Identifier(IdToken {id: 12})", token_constructor!(Token::Identifier(IdToken {id: 12})));
        assert_eq!("Token::String(String::from(\"Hello, World !\"))", token_constructor!(Token::String(String::from("Hello, World !"))));
        assert_eq!("Token::String(String::from(\"Escape \\\" \\n \\\\ chars\"))", token_constructor!(Token::String(String::from("Escape \" \n \\ chars"))));
    }

}